/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Daftarkan usaha baru beserta pemiliknya
         * @description **Satu-satunya jalur yang menciptakan usaha.** `POST /users` tidak pernah
         *     membuatnya — ia mengundang operator ke usaha yang sudah ada (BR-004).
         *
         *     Baris `owners` dan baris `users` ber-`role = 'owner'` terbit dalam satu transaksi.
         *     Gagal di tengah tidak boleh meninggalkan usaha yang tidak bisa dimasuki siapa pun.
         *
         *     **`slug` tidak ditanyakan di sini.** Ia opsional, butuh paket `usaha` ke atas, dan
         *     diisi belakangan dari `PATCH /settings` (BR-025). Tiap field di layar daftar adalah
         *     tempat orang berhenti, dan memilih subdomain adalah keputusan yang belum bisa
         *     diambil sebelum produknya terlihat.
         *
         *     Balasannya membawa sesi yang langsung jadi — pemilik tidak perlu login lagi. Tapi
         *     ia mendarat di **dinding verifikasi**, bukan dashboard: sesinya diterbitkan justru
         *     supaya ia bisa memanggil `resend` tanpa login ulang (BR-006).
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Tukar token verifikasi dengan email yang terverifikasi
         * @description Sekali pakai, umur 24 jam. Kedaluwarsa, sudah dipakai, atau tidak dikenal →
         *     `422 verification-token-invalid`.
         *
         *     Tanpa autentikasi: tautannya dibuka dari surel, dan browser yang membukanya belum
         *     tentu browser yang mendaftar. Tokennya sendiri yang jadi bukti.
         *
         *     Kedaluwarsa bukan jalan buntu — `resend` selalu tersedia (BR-006).
         */
        post: operations["verifyEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-email/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Kirim ulang surel verifikasi
         * @description Butuh sesi, bukan token verifikasi — pemanggilnya sudah login, cuma belum
         *     terverifikasi. Itu sebabnya `POST /auth/register` membalas dengan sesi.
         *
         *     3 req/jam per pengguna (§7). **Selalu tersedia**: satu-satunya hal yang bisa
         *     dilakukan akun yang belum terverifikasi adalah memverifikasi dirinya, jadi
         *     menutup jalan ini berarti menutup satu-satunya jalan keluar (BR-006).
         */
        post: operations["resendVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/accept-invitation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Terima undangan dan pasang password
         * @description Jalur yang membuat baris `users` ber-`status = 'invited'` dari `POST /users`
         *     akhirnya bisa dipakai. Ia memasang `password_hash`, menyetel `status = 'active'`,
         *     **dan mengisi `email_verified_at` sekaligus**.
         *
         *     Yang terakhir itu bukan jalan pintas: undangan hanya bisa diterima lewat tautan di
         *     emailnya, jadi menerimanya **sudah** bukti kendali atas alamat itu. Mengirim surel
         *     verifikasi kedua sesudah surel undangan adalah meminta bukti yang sama dua kali
         *     (BR-004, BR-006).
         *
         *     Balasannya sesi yang langsung jadi, dan operator ini mendarat di dashboard — bukan
         *     di dinding verifikasi, karena ia sudah melewatinya.
         */
        post: operations["acceptInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Tukar email dan password dengan access token
         * @description Usahanya diturunkan dari baris `users` — `email` unik di seluruh sistem, jadi ia
         *     menunjuk tepat satu user dan karenanya tepat satu usaha. Sengaja tidak ada parameter
         *     usaha, slug, maupun subdomain (BR-004).
         *
         *     Kalau berhasil, refresh token diset sebagai cookie httpOnly, Secure, SameSite=Lax.
         *     Ia tidak pernah ada di body respons, tempat script bisa membacanya.
         *
         *     Password salah, email tidak dikenal, dan akun nonaktif semuanya dijawab `401` yang
         *     sama. Selisih apa pun di antara ketiganya memberi tahu penyerang email mana yang ada.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotasi refresh token dan terbitkan access token baru
         * @description Membaca refresh token dari cookie, tidak pernah dari body. Tanpa autentikasi karena
         *     memang harus begitu — ini yang kamu panggil *justru karena* access token-nya sudah
         *     kedaluwarsa.
         *
         *     Setiap panggilan menerbitkan refresh token baru dan mencabut yang dipakai.
         *     **Menyodorkan token yang sudah dirotasi berarti ia dicuri**: seluruh rantai rotasi
         *     dicabut dan semua sesi user itu berakhir, bukan sekadar request ini yang ditolak.
         */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cabut refresh token yang sedang dipakai
         * @description Mencabut refresh token di cookie lalu menghapusnya. Access token tidak dicabut — ia
         *     stateless dan kedaluwarsa sendiri dalam 15 menit.
         *
         *     Idempoten: logout dua kali, atau tanpa cookie sama sekali, tetap `204`. Tidak ada yang
         *     berguna untuk diceritakan tentang sesi yang memang sudah hilang.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Usaha, peran, dan izin pengguna yang sedang masuk
         * @description Sumber kebenaran untuk klien soal siapa dirinya dan apa yang boleh ia lakukan.
         *
         *     Frontend membaca `permissions` dari sini dan **tidak merender** aksi yang tidak ada di
         *     dalamnya. Tombol nonaktif yang tetap `403` mengiklankan kemampuan yang tidak dimiliki
         *     penggunanya dan melahirkan tiket support (BR-003).
         *
         *     Jangan mem-parsing access token di klien untuk mendapat data ini. Token itu untuk
         *     server; men-decode-nya di browser membuat dua sumber kebenaran yang bisa berbeda.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Baca knob pemilik
         * @description Satu-satunya tempat knob pemilik hidup. Tidak satu pun konsumennya boleh menyimpan
         *     default-nya sendiri — itu inti BR-024, BR-027, BR-038, dan BR-057 sekaligus.
         */
        get: operations["getSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Ubah knob pemilik
         * @description Hanya peran `owner`. `operator` yang memanggilnya dibalas `403` yang **menyebut**
         *     `settings:write` di `detail` (BR-003).
         *
         *     Key yang absen dibiarkan apa adanya; `null` eksplisit adalah `422`. Slug yang sudah
         *     terisi tidak bisa dikosongkan lagi lewat endpoint ini — mencabut halaman publik
         *     usaha adalah keputusan yang belum punya kontraknya.
         */
        patch: operations["updateSettings"];
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Akun di usaha ini
         * @description Hanya peran `owner` (`users:read`). `operator` tidak boleh menyentuh endpoint ini
         *     sama sekali — bukan melihatnya lalu ditolak (BR-003).
         */
        get: operations["listUsers"];
        put?: never;
        /**
         * Undang akun ke usaha ini
         * @description Membuat baris `users` berstatus `invited` tanpa password. Tanpa endpoint ini peran
         *     `operator` ada di matriks izin tapi tidak ada cara memakainya.
         *
         *     **Email unik global.** Alamat yang sudah dipakai di usaha mana pun ditolak
         *     `422 email-taken`, dan itu yang membuat login cukup email + password (BR-004).
         */
        post: operations["inviteUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Nonaktifkan akun
         * @description Menyetel `users.status = 'disabled'`. **Barisnya tidak dihapus** — `created_by` di
         *     tabel lain harus tetap bisa dijelaskan, dan riwayat yang menunjuk akun hilang tidak
         *     bisa dibaca siapa pun.
         *
         *     Sesi yang dicabut mati dalam **≤ 15 menit**, batas TTL access token. Refresh yang
         *     datang sesudahnya ditolak, jadi tidak ada sesi yang hidup lebih lama dari itu.
         */
        delete: operations["disableUser"];
        options?: never;
        head?: never;
        /**
         * Ubah peran atau status akun
         * @description `email` dan `owner_id` tidak bisa diubah. Satu user milik tepat satu usaha, dan
         *     alamatnya yang menunjuk usaha itu saat login (BR-004).
         *
         *     Id milik usaha lain dibalas **`404`, bukan `403`** — baris usaha lain tidak bisa
         *     dibedakan dari baris yang memang tidak ada (BR-001).
         */
        patch: operations["updateUser"];
        trace?: never;
    };
    "/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Jenis barang di usaha ini
         * @description Jenis barang, bukan unit fisiknya (BR-010). Operator ikut membacanya — seluruh
         *     pekerjaannya, dari booking sampai serah-terima, menunjuk katalog ini.
         */
        get: operations["listResources"];
        put?: never;
        /**
         * Daftarkan jenis barang baru
         * @description Hanya peran `owner` (`resources:write`).
         *
         *     **`pricing_unit` tidak ada di body dan memang tidak bisa dikirim.** Server
         *     mengisinya dari `owners.business_type` saat barisnya dibuat (BR-012, BR-017),
         *     dan karena ia tidak terdaftar di `ResourceCreate`, klien yang digenerate tidak
         *     punya field-nya sama sekali — penolakan di waktu kompilasi, bukan `422`.
         *
         *     Empat nominal boleh `null` atau dihilangkan, dan dua-duanya berarti aturannya
         *     tidak berlaku untuk barang ini. **`0` ditolak database** (BR-016).
         */
        post: operations["createResource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Satu jenis barang */
        get: operations["getResource"];
        put?: never;
        post?: never;
        /**
         * Hapus jenis barang
         * @description Hanya peran `owner` (`records:delete`) — BR-003 melarang operator menghapus
         *     apa pun, dan itu sebagian besar alasan seorang juragan mau membagikan akun.
         *
         *     Soft delete: `deleted_at` terisi, barisnya tetap ada. Booking lama menunjuk
         *     snapshot-nya sendiri (BR-014), jadi riwayat tetap terbaca.
         */
        delete: operations["deleteResource"];
        options?: never;
        head?: never;
        /**
         * Ubah jenis barang
         * @description Hanya peran `owner` (`resources:write`). Field `base_price`, `deposit_amount`,
         *     dan `late_fee_per_unit` butuh **`pricing:write`** di atas itu — BR-003 menyebut
         *     nominalnya, bukan endpoint-nya.
         *
         *     **Mengubah harga tidak menyentuh booking mana pun** (BR-014). Responsnya
         *     menyebut berapa booking berjalan yang tetap memakai harga lama, supaya pemilik
         *     tidak perlu menebak.
         *
         *     Untuk keempat nominal, **`null` eksplisit adalah satu-satunya cara mencabut**
         *     nilai yang sudah ada; menghilangkan key-nya membiarkan nilainya apa adanya.
         *     Itu pengecualian yang disengaja terhadap konvensi "`null` eksplisit = `422`",
         *     yang berlaku untuk field yang dikelola server.
         */
        patch: operations["updateResource"];
        trace?: never;
    };
    "/resources/{id}/units": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /**
         * Unit fisik dari satu jenis barang
         * @description Tiga Avanza adalah satu `Resource` dan tiga `ResourceUnit` — booking selalu
         *     menunjuk satu unit, tidak pernah hanya jenisnya (BR-010).
         */
        get: operations["listUnits"];
        put?: never;
        /**
         * Tambah unit fisik
         * @description Hanya peran `owner` (`units:write`).
         *
         *     `code` **dikirim klien** — plat nomor atau nomor seri, yang dipakai operator
         *     mengenali barangnya secara fisik (BR-011). Jangan tertukar dengan
         *     `bookings.code`, yang dihasilkan server dari pencacah.
         *
         *     Kode yang sudah dipakai di usaha ini dibalas `422` dengan `errors[].field`
         *     bernilai `code`. Usaha lain boleh memakai kode yang sama.
         */
        post: operations["createUnit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/units/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Hapus unit
         * @description Hanya peran `owner` (`records:delete`). Soft delete, dan kodenya kembali bisa
         *     dipakai — unique index-nya `WHERE deleted_at IS NULL` (BR-011).
         */
        delete: operations["deleteUnit"];
        options?: never;
        head?: never;
        /**
         * Ubah unit, termasuk statusnya
         * @description Hanya peran `owner` (`units:write`).
         *
         *     **Mengubah status ke `maintenance` atau `retired` tidak menghapus dan tidak
         *     membatalkan booking yang sudah ada** untuk unit itu. Responsnya `200` beserta
         *     daftar booking terdampak, dan pemilik yang memutuskan (BR-013). Menolak
         *     perubahannya berarti memaksa juragan membatalkan sendiri satu per satu sebelum
         *     boleh bilang mobilnya di bengkel.
         *
         *     Unit di luar `active` hilang dari pencarian ketersediaan, tapi tetap punya
         *     lajur `maintenance` di kalender; `retired` tidak punya lajur sama sekali.
         *
         *     Tidak ada `GET /units/{id}` — daftarnya dibaca lewat jenis barangnya.
         */
        patch: operations["updateUnit"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginRequest: {
            /**
             * Format: email
             * @example budi@rentalbudi.id
             */
            email: string;
            /** Format: password */
            password: string;
        };
        /**
         * @description Empat field, dan tidak lebih. Tiap satu yang ditambahkan adalah tempat orang
         *     berhenti mengisi (BR-005).
         */
        RegisterRequest: {
            /**
             * Format: email
             * @description Unik di seluruh sistem, bukan per usaha (BR-004).
             * @example budi@contoh.id
             */
            email: string;
            /** Format: password */
            password: string;
            /** @example Rental Budi */
            business_name: string;
            business_type: components["schemas"]["BusinessType"];
        };
        /**
         * @description Preset pasar, dipilih sekali saat mendaftar. **Ia yang menentukan `pricing_unit`
         *     seluruh resource pemilik itu** — juragan tidak pernah mengisi satuan harga di tiap
         *     barang (BR-012, BR-017).
         *
         *     Enamnya ada di enum karena skema mengenal keenamnya, tapi **cuma dua yang dibuka di
         *     fase 1**: `vehicle_rental` dan `equipment_rental`, dua-duanya bersatuan `day`.
         *     `boarding_house` dan `apartment` fase 2, `venue` fase 3, `clinic` fase 4 — satuan
         *     `clinic` sengaja belum diputuskan, bukan ditebak.
         *
         *     Layar daftar fase 1 karena itu merender **dua pilihan**, dengan bahasa juragan
         *     ("rental mobil & motor", "rental alat"), bukan nama enum ini.
         * @example vehicle_rental
         * @enum {string}
         */
        BusinessType: "vehicle_rental" | "equipment_rental" | "boarding_house" | "apartment" | "venue" | "clinic";
        /**
         * @description Dikembalikan login dan refresh. Membawa semua yang dibutuhkan klien untuk merender
         *     kerangka aplikasi tanpa request kedua.
         *
         *     Refresh token **tidak** ada di sini — ia di cookie httpOnly, di luar jangkauan script
         *     mana pun di halaman itu.
         */
        Session: {
            /** @description JWT. Disimpan di memori saja, tidak pernah di localStorage. */
            access_token: string;
            /**
             * @description Detik sampai access token kedaluwarsa.
             * @example 900
             */
            expires_in: number;
            user: components["schemas"]["SessionUser"];
            owner: components["schemas"]["SessionOwner"];
        };
        /**
         * @description Bentuk yang sama dengan `Session` dikurangi tokennya. `GET /me` dipanggil saat reload
         *     halaman, ketika access token sudah ada di memori dan yang dibutuhkan cuma konteksnya.
         */
        Me: {
            user: components["schemas"]["SessionUser"];
            owner: components["schemas"]["SessionOwner"];
        };
        SessionUser: {
            /** Format: uuid */
            id: string;
            name: string;
            /**
             * Format: date-time
             * @description `null` selama email belum terverifikasi. Frontend merender dinding verifikasi
             *     dari field ini, bukan dari menebak lewat `403 email-not-verified` — gerbang itu
             *     bisa muncul di endpoint mana pun, jadi menebaknya berarti menebak di tiap layar
             *     (BR-006).
             */
            email_verified_at: string | null;
            /**
             * @description Satu peran per orang, karena satu orang punya satu usaha (BR-003, BR-004).
             * @enum {string}
             */
            role: "owner" | "operator";
            /**
             * @description String `resource:action` yang diberikan peran itu. Klien **menyembunyikan** aksi
             *     yang tidak ada di sini, bukan menonaktifkannya — tombol yang `403` mengiklankan
             *     kemampuan yang tidak dimiliki penggunanya.
             */
            permissions: string[];
        };
        /**
         * @description Usaha tempat user ini bekerja. Tepat satu, selalu — tidak ada daftar dan tidak ada
         *     pengalih (BR-004).
         *
         *     Tidak ada `currency`: uang di sistem ini selalu rupiah penuh sebagai integer
         *     (`120000` = Rp 120.000). Tidak ada `timezone`: waktu di kawat selalu UTC, dan
         *     Asia/Jakarta urusan render di frontend.
         */
        SessionOwner: {
            /** Format: uuid */
            id: string;
            /** @example Rental Budi */
            name: string;
            /**
             * @description Label subdomain usaha ini — `rentalbudi` berarti `rentalbudi.sewain.id` (BR-025).
             *
             *     **`null` adalah keadaan awal setiap usaha**, bukan kasus pinggir: slug tidak
             *     ditanyakan saat daftar (BR-005) dan diisi belakangan dari `PATCH /settings`.
             *     Pemilik tanpa slug tidak punya host sama sekali — katalog publik maupun portal
             *     penyewa ikut tidak ada. Karena itu ia tidak `required`: usaha yang baru saja
             *     terbit lewat `POST /auth/register` tidak bisa memenuhinya.
             * @example rentalbudi
             */
            slug?: string | null;
        };
        /**
         * @description Knob pemilik, semuanya. Tiap satu ada karena sebuah aturan bisnis melarang
         *     meng-hardcode-nya, dan `PATCH /settings` satu-satunya tempat mereka disetel.
         */
        Settings: {
            /**
             * @description Sama dengan `SessionOwner.slug`: `null` adalah keadaan awal, dan di sinilah ia
             *     diisi — bukan saat daftar (BR-005, BR-025).
             *
             *     **Belum ada yang membacanya sampai M5** (`S1-051`, `S1-060`). Ia tersimpan dan
             *     tervalidasi di sini, tapi halaman publiknya baru hidup 12 minggu kemudian, dan
             *     layar pengaturan wajib jujur soal itu.
             * @example rentalbudi
             */
            slug: string | null;
            /**
             * @description Awalan kode booking, `SWN-0001`. Mengubahnya **tidak** menyentuh kode yang sudah
             *     terbit dan **tidak** me-reset pencacahnya (BR-024).
             * @default SWN
             * @example RBD
             */
            booking_code_prefix: string;
            /**
             * @description Kalau menyala, pengambilan ditolak selama invoicenya belum lunas (BR-038).
             * @default false
             */
            require_payment_before_pickup: boolean;
            /**
             * @description Umur draft dari halaman publik sebelum dibatalkan otomatis (BR-027).
             * @default 24
             */
            draft_expiry_hours: number;
            /**
             * @description Tenggat bayar sejak invoice terbit. **`0` ditolak database** — tenggat nol berarti
             *     invoice yang lewat tempo pada detik ia terbit (BR-057).
             * @default 24
             */
            payment_due_hours: number;
            /**
             * @description Tenggang sesudah `start_at` sebelum booking ditandai `no_show`. **`0` diterima**,
             *     dan itu bedanya dengan `payment_due_hours` — pemilik yang mau membebaskan unitnya
             *     di hari yang sama memang menyetelnya nol (BR-057).
             * @default 3
             */
            no_show_tolerance_hours: number;
            /**
             * @description Pengingat H-1 ambil (BR-070).
             * @default true
             */
            notify_pickup_reminder: boolean;
            /**
             * @description Pengingat H-1 balik (BR-070).
             * @default true
             */
            notify_return_reminder: boolean;
            /**
             * @description Pengingat saat kondisi telat terpenuhi (BR-070).
             * @default true
             */
            notify_overdue_reminder: boolean;
        };
        /**
         * @description Semua field opsional. Key yang absen dibiarkan apa adanya; `null` eksplisit adalah
         *     `422` — menghilangkan field dan mengirim `null` bukan hal yang sama.
         */
        SettingsUpdate: {
            /** @example rentalbudi */
            slug?: string;
            booking_code_prefix?: string;
            require_payment_before_pickup?: boolean;
            draft_expiry_hours?: number;
            payment_due_hours?: number;
            no_show_tolerance_hours?: number;
            notify_pickup_reminder?: boolean;
            notify_return_reminder?: boolean;
            notify_overdue_reminder?: boolean;
        };
        /**
         * @description Akun di usaha ini. Tidak pernah memuat `password_hash` maupun `owner_id` — yang
         *     pertama rahasia, yang kedua sudah tersirat dari usaha pemanggilnya.
         */
        User: {
            /** Format: uuid */
            id: string;
            /**
             * Format: email
             * @description Unik di seluruh sistem, bukan per usaha (BR-004).
             */
            email: string;
            name: string;
            /** @enum {string} */
            role: "owner" | "operator";
            /**
             * @description `invited` sampai undangannya diterima, `disabled` sesudah dinonaktifkan. Nol
             *     endpoint di API ini yang menghapus baris `users`.
             * @enum {string}
             */
            status: "invited" | "active" | "disabled";
            /** Format: date-time */
            last_login_at?: string | null;
        };
        InviteUserRequest: {
            /** Format: email */
            email: string;
            name: string;
            /**
             * @default operator
             * @enum {string}
             */
            role: "owner" | "operator";
        };
        /** @description Minimal satu field. `email` dan `owner_id` sengaja tidak ada di sini. */
        UpdateUserRequest: {
            /** @enum {string} */
            role?: "owner" | "operator";
            /**
             * @description `invited` tidak ada di sini — ia dikelola server dan cuma berlaku sebelum
             *     undangannya diterima.
             * @enum {string}
             */
            status?: "active" | "disabled";
        };
        /**
         * @description Satuan harga. **Diisi server dari `owners.business_type`, tidak pernah dikirim
         *     klien** (BR-012, BR-017) — karena itu ia ada di `Resource` tapi tidak di
         *     `ResourceCreate` maupun `ResourceUpdate`.
         *
         *     Ia dipakai dua kali di perhitungan uang: `duration_qty`, dan rumus denda telat
         *     `ceil(kelebihan / pricing_unit)` (BR-046). Nilai asing bukan data kotor, ia
         *     tagihan yang salah — jadi keempatnya juga ditegakkan CHECK di database.
         *
         *     Fase 1 selalu `day`: kedua preset yang dibuka (`vehicle_rental`,
         *     `equipment_rental`) cuma punya satu satuan, jadi juragan rental tidak pernah
         *     melihat field satuan harga di layar mana pun.
         * @enum {string}
         */
        PricingUnit: "hour" | "day" | "week" | "month";
        /**
         * @description `inactive` berarti barang itu tidak ditawarkan lagi tanpa menghapus riwayatnya.
         * @enum {string}
         */
        ResourceStatus: "active" | "inactive";
        /**
         * @description Hanya `active` yang muncul di pencarian ketersediaan (BR-013). `maintenance`
         *     tetap punya lajur di kalender; `retired` tidak punya lajur sama sekali.
         *
         *     Tidak ada `rented` di sini, dan itu disengaja: "sedang disewa" adalah turunan
         *     dari booking ber-status `picked_up`, bukan keadaan yang disimpan (BR-023).
         *     Dua sumber untuk satu fakta berarti satu di antaranya akan salah.
         * @enum {string}
         */
        UnitStatus: "active" | "maintenance" | "retired";
        /**
         * @description Jenis barang. Unit fisiknya ada di `ResourceUnit`, dan booking selalu menunjuk
         *     unit — tidak pernah hanya jenisnya (BR-010).
         *
         *     **Keempat nominal dan `category` wajib ada di respons walau bernilai `null`.**
         *     Di sebuah *request* "tidak dikirim" dan "`null`" adalah dua perintah berbeda;
         *     di respons tidak ada bedanya — barangnya berdeposit atau tidak. Menghilangkan
         *     key-nya memaksa klien menebak mana dari dua arti itu yang dimaksud, jadi
         *     field-nya selalu terbit dan `null` mengatakannya sendiri.
         */
        Resource: {
            /** Format: uuid */
            id: string;
            /** @example Avanza 2021 */
            name: string;
            /** @example Mobil */
            category: string | null;
            pricing_unit: components["schemas"]["PricingUnit"];
            /**
             * Format: int64
             * @description Rupiah penuh, bukan minor unit: `350000` berarti Rp 350.000.
             * @example 350000
             */
            base_price: number;
            /**
             * Format: int64
             * @description `null` berarti barang ini tidak berdeposit — BR-045 tidak menerbitkan
             *     barisnya, dan BR-048/BR-049 tidak berlaku. **`0` ditolak database**: tidak
             *     ada kasus rental yang butuh deposit nol rupiah, dan kalau `0` dan `null`
             *     sama-sama berarti "tanpa deposit", tidak ada laporan yang bisa
             *     membedakannya lagi (BR-016).
             * @example 500000
             */
            deposit_amount: number | null;
            /**
             * Format: int64
             * @description `null` berarti tanpa denda telat. Yang hilang cuma tagihannya —
             *     peringatan terlambat dan pengingatnya tetap jalan (BR-016, BR-041).
             */
            late_fee_per_unit: number | null;
            /** @description `null` berarti tanpa batas bawah, bukan nol (BR-016, BR-021). */
            min_duration: number | null;
            /** @description `null` berarti tanpa batas atas. `max < min` ditolak database. */
            max_duration: number | null;
            /**
             * @description Jeda wajib sesudah `end_at` sebelum unit yang sama bisa disewa lagi
             *     (BR-015). **Satu-satunya field opsional di sini yang tidak boleh kosong:**
             *     `end_at + NULL` menghasilkan NULL, dan rentang tak berbatas ke atas akan
             *     bentrok dengan seluruh booking masa depan unit itu. "Tanpa jeda" sudah
             *     persis sama dengan `0`.
             * @default 0
             * @example 120
             */
            buffer_minutes: number;
            /**
             * @description Tidak ikut yang boleh `null`, walau BR-016 mendaftarnya di tabel yang sama:
             *     boolean bernilai `NULL` cuma menambah keadaan ketiga yang tidak berarti apa
             *     pun. "Tidak wajib" sudah persis sama dengan `false` (BR-085).
             * @default false
             */
            requires_id_verification: boolean;
            status: components["schemas"]["ResourceStatus"];
            /**
             * @description Unit `active` yang dimiliki jenis barang ini. Dihitung server. Nol berarti
             *     barang ini tidak akan pernah muncul di pencarian ketersediaan, berapa pun
             *     statusnya sendiri (BR-010) — dan layar katalog wajib mengatakannya.
             */
            unit_count: number;
        };
        /**
         * @description `pricing_unit` **sengaja tidak ada di sini** dan tidak akan pernah ada:
         *     server mengisinya dari preset pemiliknya (BR-017). Begitu juga `id`, `owner_id`,
         *     dan `unit_count`.
         */
        ResourceCreate: {
            name: string;
            category?: string;
            /** Format: int64 */
            base_price: number;
            /** Format: int64 */
            deposit_amount?: number | null;
            /** Format: int64 */
            late_fee_per_unit?: number | null;
            min_duration?: number | null;
            max_duration?: number | null;
            /** @default 0 */
            buffer_minutes: number;
            /** @default false */
            requires_id_verification: boolean;
        };
        /**
         * @description Semua field opsional, dan key yang absen membiarkan nilainya apa adanya.
         *
         *     **Untuk keempat nominal, `null` eksplisit mencabut nilainya** — itu satu-satunya
         *     caranya, dan itu pengecualian yang disengaja terhadap aturan umum "`null`
         *     eksplisit adalah `422`" yang berlaku untuk field yang dikelola server
         *     (`04-api-spec.md` §3.2). `buffer_minutes` tidak ikut: ia `NOT NULL`.
         */
        ResourceUpdate: {
            name?: string;
            category?: string | null;
            /** Format: int64 */
            base_price?: number;
            /** Format: int64 */
            deposit_amount?: number | null;
            /** Format: int64 */
            late_fee_per_unit?: number | null;
            min_duration?: number | null;
            max_duration?: number | null;
            buffer_minutes?: number;
            requires_id_verification?: boolean;
            status?: components["schemas"]["ResourceStatus"];
        };
        ResourceUpdated: components["schemas"]["Resource"] & {
            /**
             * @description Booking berjalan yang **tetap memakai harga lama**, karena harga
             *     di-snapshot saat booking dibuat dan tidak pernah dibaca ulang (BR-014).
             *     Ia ada supaya pemilik yang menaikkan harga tahu persis berapa banyak
             *     yang tidak ikut naik, tanpa menebak.
             *
             *     **Selalu `0` sampai `S1-022` membuat tabel `bookings`.** Bentuk
             *     responsnya mendarat sekarang supaya layarnya ditulis sekali; yang
             *     menyusul cuma isi query-nya.
             */
            active_bookings: number;
        };
        /**
         * @description Barang fisiknya. Tiga Avanza adalah satu `Resource` dan tiga baris di sini,
         *     dan kalender menampilkan tiga lajur terpisah.
         */
        ResourceUnit: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            resource_id: string;
            /**
             * @description Plat nomor atau nomor seri — yang dipakai operator mengenali barangnya
             *     secara fisik. Unik per usaha, bukan global: dua rental boleh sama-sama
             *     punya `B 1234 XY` (BR-011).
             *
             *     **Tidak pernah muncul di permukaan publik** (BR-025).
             * @example B 1234 XY
             */
            code: string;
            /**
             * @description Nama panggilan, buat dibacakan lewat telepon.
             * @example Avanza Putih
             */
            label: string | null;
            status: components["schemas"]["UnitStatus"];
            /**
             * Format: int64
             * @description Odometer atau jam pakai terakhir. Biasanya diisi serah-terima (`S1-035`);
             *     di sini supaya unit baru bisa mulai dari angka yang benar.
             */
            meter_value: number | null;
            condition_notes: string | null;
        };
        UnitCreate: {
            code: string;
            label?: string;
            /** Format: int64 */
            meter_value?: number | null;
            condition_notes?: string;
        };
        /**
         * @description Semua field opsional. `resource_id` tidak ada di sini — memindahkan unit ke
         *     jenis barang lain akan membuat snapshot booking lama menunjuk jenis yang tidak
         *     pernah disewa (BR-014), dan itu perubahan kontrak, bukan satu field.
         */
        UnitUpdate: {
            code?: string;
            label?: string | null;
            status?: components["schemas"]["UnitStatus"];
            /** Format: int64 */
            meter_value?: number | null;
            condition_notes?: string | null;
        };
        UnitUpdated: components["schemas"]["ResourceUnit"] & {
            warning: components["schemas"]["UnitWarning"];
        };
        /**
         * @description Apa yang terdampak oleh perubahan ini. Ia **peringatan, bukan penolakan**:
         *     barisnya sudah berubah waktu badan ini dibaca (BR-013).
         */
        UnitWarning: {
            /**
             * @description Booking yang sudah ada untuk unit ini dan **tidak** dibatalkan maupun
             *     dihapus. Pemilik yang memutuskan apa yang terjadi pada masing-masing.
             *
             *     **Selalu kosong sampai `S1-022` membuat tabel `bookings`.**
             */
            affected_bookings: components["schemas"]["AffectedBooking"][];
        };
        AffectedBooking: {
            /** @example SWN-0043 */
            code: string;
            /** Format: date-time */
            start_at: string;
            /** Format: date-time */
            end_at: string;
            status: string;
        };
        /**
         * @description Kode error generik yang dipakai setiap endpoint sebelum sampai ke aturan bisnisnya.
         *     Kode spesifik per aturan bisnis ada di `04-api-spec.md` §2 dan ditambahkan oleh item
         *     backlog yang memilikinya.
         *
         *     Kodenya juga jadi segmen terakhir URI `Problem.type`, dan memakai **hyphen**, bukan
         *     underscore.
         * @enum {string}
         */
        ErrorCode: "unauthenticated" | "permission-denied" | "validation-failed" | "not-found" | "rate-limited" | "internal" | "email-taken" | "slug-taken" | "slug-invalid" | "email-not-verified" | "verification-token-invalid" | "request-in-flight";
        /**
         * @description Satu detail per-field di dalam `Problem`. Ia membawa apa pun yang dibutuhkan kegagalan
         *     spesifiknya, jadi properti tambahan diizinkan secara desain.
         */
        ProblemError: {
            /** @example email */
            field: string;
            detail?: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * @description RFC 9457 `application/problem+json`. Setiap respons error di API ini memakainya.
         *
         *     `trace_id` adalah trace id OpenTelemetry — tiket support yang mengutipnya langsung
         *     menunjuk ke span-nya. Tidak ada field `code` terpisah: kodenya adalah segmen terakhir
         *     `type` (BR-092).
         */
        Problem: {
            /**
             * Format: uri
             * @example https://sewain.id/problems/permission-denied
             */
            type: string;
            /** @example Tidak punya izin */
            title: string;
            /** @example 403 */
            status: number;
            /** @example Aksi ini butuh izin bookings:write. */
            detail?: string;
            /** @example /api/v1/bookings/01926f3a-0000-7000-8000-000000000000 */
            instance?: string;
            /** @example 4bf92f3577b34da6a3ce929d0e0e4736 */
            trace_id: string;
            errors?: components["schemas"]["ProblemError"][];
        };
    };
    responses: {
        /** @description Request tidak berbentuk. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Kredensial tidak ada, kedaluwarsa, atau tidak sah. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description Terautentikasi tapi tidak diizinkan. **`detail` menyebut izin yang dibutuhkan**, supaya
         *     pemanggil bisa membedakan "kamu tidak bisa melakukan ini" dari "kamu belum bisa, minta
         *     izin `bookings:write`" (BR-003).
         */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description Tidak ada data seperti itu **di usaha ini**. Baris milik usaha lain tidak bisa
         *     dibedakan dari baris yang memang tidak ada, dan itu memang yang diinginkan — selisih
         *     respons antar kasus adalah cara katalog usaha lain bocor (BR-001, BR-030).
         */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description Bentrok dengan keadaan sekarang. Di fase ini: `request-in-flight` ketika
         *     `Idempotency-Key` yang sama masih diproses (BR-090).
         */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description Validasi gagal. Juga dikembalikan ketika klien mengirim field yang dikelola server saat
         *     update, atau mengirim `null` padahal key-nya seharusnya cukup diabaikan — dua hal itu
         *     tidak sama.
         */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Batas laju terlampaui. Lihat header `RateLimit-*`. */
        TooManyRequests: {
            headers: {
                "RateLimit-Limit": components["headers"]["RateLimit-Limit"];
                "RateLimit-Remaining": components["headers"]["RateLimit-Remaining"];
                "RateLimit-Reset": components["headers"]["RateLimit-Reset"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description Ukuran halaman. Berpasangan dengan `cursor`; tidak ada `offset` di API ini. */
        Limit: number;
        /**
         * @description Cursor buram dari halaman sebelumnya. Hanya paginasi cursor — `offset` yang dalam di
         *     tabel besar adalah sequential scan, jadi parameternya tidak ada.
         */
        Cursor: string;
        /**
         * @description UUID yang dibuat klien, **satu per niat pengguna** — bukan satu per percobaan jaringan.
         *     Klien yang membuat kunci baru setiap retry sudah membatalkan seluruh gunanya.
         *
         *     Kunci yang sama dijalankan sekali; panggilan berikutnya memutar ulang respons pertama
         *     bulat-bulat. Kunci yang masih berjalan dijawab `409 request-in-flight` (BR-090).
         */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: {
        /** @description Request yang diizinkan dalam jendela saat ini. */
        "RateLimit-Limit": number;
        /** @description Sisa request dalam jendela saat ini. */
        "RateLimit-Remaining": number;
        /** @description Detik sampai jendelanya reset. */
        "RateLimit-Reset": number;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Usaha dan pemiliknya terbit. Sesi ikut di dalamnya. */
            201: {
                headers: {
                    /** @description Refresh token, httpOnly, Secure, SameSite=Lax, host-only. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            422: components["responses"]["UnprocessableEntity"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    verifyEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    token: string;
                };
            };
        };
        responses: {
            /** @description Terverifikasi. `users.email_verified_at` terisi. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    resendVerification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Surel dikirim ulang ke alamat terdaftar. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    acceptInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    token: string;
                    /** Format: password */
                    password: string;
                };
            };
        };
        responses: {
            /** @description Undangan diterima. Akun aktif dan terverifikasi. */
            200: {
                headers: {
                    /** @description Refresh token, httpOnly, Secure, SameSite=Lax, host-only. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Berhasil masuk. */
            200: {
                headers: {
                    /** @description Refresh token, httpOnly, Secure, SameSite=Lax. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["UnprocessableEntity"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Terotasi. */
            200: {
                headers: {
                    /** @description Refresh token baru. Yang lama sudah dicabut. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Keluar. Cookie dihapus. */
            204: {
                headers: {
                    /** @description Cookie refresh yang sudah kedaluwarsa. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sesi yang sedang berjalan. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Knob usaha ini. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    updateSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdate"];
            };
        };
        responses: {
            /** @description Knob sesudah diubah. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Akun di usaha ini. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    inviteUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteUserRequest"];
            };
        };
        responses: {
            /** @description Akun terbit, menunggu undangan diterima. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    disableUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Akun nonaktif. Barisnya tetap ada. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description Akun sesudah diubah. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    listResources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Jenis barang di usaha ini. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resource"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createResource: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResourceCreate"];
            };
        };
        responses: {
            /** @description Jenis barang terbit. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resource"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    getResource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Jenis barang itu. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resource"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteResource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Jenis barang terhapus. Barisnya tetap ada. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateResource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResourceUpdate"];
            };
        };
        responses: {
            /** @description Jenis barang sesudah diubah, beserta dampaknya ke booking. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceUpdated"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    listUnits: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Unit fisik jenis barang itu. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceUnit"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createUnit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UnitCreate"];
            };
        };
        responses: {
            /** @description Unit terbit. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceUnit"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    deleteUnit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Unit terhapus. Barisnya tetap ada. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateUnit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UnitUpdate"];
            };
        };
        responses: {
            /** @description Unit sesudah diubah, beserta peringatannya. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnitUpdated"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
}
